language: python
python:
  - 3.6
  - 3.7
dist: bionic
addons:
  apt:
    packages:
      - libsqlcipher-dev
install:
  - python setup.py build_ext -i
script:
  - PYTHONPATH=".:$PYTHONPATH" python test/
